-- Tabelas iniciais para salvar dados reais no Supabase.
-- A peca usa origem_id como vinculo com a origem. O texto da origem fica apenas para exibicao.

create table if not exists public.origens (
  id bigint generated by default as identity primary key,
  tipo text not null,
  descricao text not null,
  valor_pago numeric(12, 2) not null default 0,
  data_compra date not null,
  observacoes text,
  criado_em timestamptz not null default now()
);

create table if not exists public.pecas (
  id bigint generated by default as identity primary key,
  origem_id bigint not null references public.origens(id),
  nome text not null,
  sku text,
  categoria text not null,
  quantidade integer not null default 1,
  quantidade_vendida integer not null default 0,
  status text not null default 'em_estoque',
  custo numeric(12, 2) not null default 0,
  tipo_custo text not null default 'real',
  preco_venda numeric(12, 2) not null default 0,
  observacoes text,
  criado_em timestamptz not null default now(),
  constraint pecas_tipo_custo_check check (tipo_custo in ('real', 'rateado', 'simbolico')),
  constraint pecas_quantidade_check check (quantidade >= 0),
  constraint pecas_quantidade_vendida_check check (quantidade_vendida >= 0)
);
