-- Tabelas iniciais para salvar dados reais no Supabase.
-- A peca usa origem_id como vinculo com a origem. O texto da origem fica apenas para exibicao.

create table if not exists public.origens (
  id bigint generated by default as identity primary key,
  tipo_origem text,
  descricao text not null,
  fornecedor_id bigint,
  custo_total numeric(12, 2),
  custo_tipo text,
  produto_sku text,
  quantidade_total integer not null default 0,
  data_entrada date,
  observacoes text,
  created_at timestamptz not null default now(),
  tipo text,
  valor_pago numeric(12, 2) not null default 0,
  data_compra date not null default current_date,
  criado_em timestamptz not null default now()
);

alter table public.origens add column if not exists tipo_origem text;
alter table public.origens add column if not exists tipo text;
alter table public.origens add column if not exists descricao text;
alter table public.origens add column if not exists fornecedor_id bigint;
alter table public.origens add column if not exists custo_total numeric(12, 2);
alter table public.origens add column if not exists custo_tipo text;
alter table public.origens add column if not exists produto_sku text;
alter table public.origens add column if not exists quantidade_total integer default 0;
alter table public.origens add column if not exists data_entrada date;
alter table public.origens add column if not exists valor_pago numeric(12, 2) default 0;
alter table public.origens add column if not exists data_compra date default current_date;
alter table public.origens add column if not exists observacoes text;
alter table public.origens add column if not exists created_at timestamptz default now();
alter table public.origens add column if not exists criado_em timestamptz default now();

update public.origens
set tipo = coalesce(tipo, tipo_origem, 'Origem')
where tipo is null;

update public.origens
set valor_pago = coalesce(valor_pago, custo_total, 0)
where valor_pago is null;

update public.origens
set quantidade_total = 0
where quantidade_total is null;

update public.origens
set data_compra = current_date
where data_compra is null;

alter table public.origens alter column valor_pago set default 0;
alter table public.origens alter column quantidade_total set default 0;
alter table public.origens alter column data_compra set default current_date;

create table if not exists public.pecas (
  id bigint generated by default as identity primary key,
  origem_id bigint not null references public.origens(id),
  produto_id bigint,
  nome_peca text not null,
  sku text,
  custo_atribuido numeric(12, 2),
  tipo_custo_atribuido text not null default 'real',
  preco_sugerido numeric(12, 2) not null default 0,
  status text not null default 'em_estoque',
  preparada boolean not null default false,
  observacoes text,
  created_at timestamptz not null default now(),
  custo_total numeric(12, 2),
  custo numeric(12, 2) not null default 0,
  quantidade integer not null default 1,
  quantidade_vendida integer not null default 0,
  constraint pecas_tipo_custo_atribuido_check check (tipo_custo_atribuido in ('real', 'rateado', 'simbolico')),
  constraint pecas_quantidade_check check (quantidade >= 0),
  constraint pecas_quantidade_vendida_check check (quantidade_vendida >= 0)
);

alter table public.pecas add column if not exists origem_id bigint;
alter table public.pecas add column if not exists produto_id bigint;
alter table public.pecas add column if not exists nome_peca text;
alter table public.pecas add column if not exists sku text;
alter table public.pecas add column if not exists custo_atribuido numeric(12, 2);
alter table public.pecas add column if not exists tipo_custo_atribuido text default 'real';
alter table public.pecas add column if not exists preco_sugerido numeric(12, 2) default 0;
alter table public.pecas add column if not exists status text default 'em_estoque';
alter table public.pecas add column if not exists preparada boolean default false;
alter table public.pecas add column if not exists observacoes text;
alter table public.pecas add column if not exists created_at timestamptz default now();
alter table public.pecas add column if not exists custo_total numeric(12, 2);
alter table public.pecas add column if not exists custo numeric(12, 2) default 0;
alter table public.pecas add column if not exists quantidade integer default 1;
alter table public.pecas add column if not exists quantidade_vendida integer default 0;

update public.pecas
set nome_peca = concat('Peca ', id)
where nome_peca is null or trim(nome_peca) = '';

update public.pecas
set custo_total = coalesce(custo_total, custo_atribuido, custo, 0)
where custo_total is null;

update public.pecas
set custo = coalesce(custo, custo_total, 0)
where custo is null;

update public.pecas
set custo_atribuido = coalesce(custo_atribuido, custo_total, custo, 0)
where custo_atribuido is null;

update public.pecas
set tipo_custo_atribuido = 'real'
where tipo_custo_atribuido is null or trim(tipo_custo_atribuido) = '';

update public.pecas
set preco_sugerido = 0
where preco_sugerido is null;

update public.pecas
set status = 'em_estoque'
where status is null or trim(status) = '';

update public.pecas
set preparada = false
where preparada is null;

update public.pecas
set quantidade = 1
where quantidade is null;

update public.pecas
set quantidade_vendida = 0
where quantidade_vendida is null;

alter table public.pecas alter column custo set default 0;
alter table public.pecas alter column nome_peca set not null;
alter table public.pecas alter column tipo_custo_atribuido set default 'real';
alter table public.pecas alter column tipo_custo_atribuido set not null;
alter table public.pecas alter column preco_sugerido set default 0;
alter table public.pecas alter column preco_sugerido set not null;
alter table public.pecas alter column status set default 'em_estoque';
alter table public.pecas alter column status set not null;
alter table public.pecas alter column preparada set default false;
alter table public.pecas alter column preparada set not null;
alter table public.pecas alter column quantidade set default 1;
alter table public.pecas alter column quantidade set not null;
alter table public.pecas alter column quantidade_vendida set default 0;
alter table public.pecas alter column quantidade_vendida set not null;

create table if not exists public.custos_peca (
  id bigint generated by default as identity primary key,
  peca_id bigint not null references public.pecas(id),
  tipo_custo text not null,
  descricao text,
  valor numeric(12, 2) not null default 0,
  data_custo date not null default current_date,
  created_at timestamptz not null default now(),
  constraint custos_peca_valor_check check (valor >= 0)
);

alter table public.custos_peca add column if not exists created_at timestamptz default now();

create table if not exists public.vendas (
  id bigint generated by default as identity primary key,
  cliente_id bigint,
  data_venda date not null default current_date,
  valor_total numeric(12, 2),
  canal_venda text,
  observacoes text,
  created_at timestamptz not null default now(),
  peca_id bigint not null references public.pecas(id),
  quantidade_vendida integer not null,
  valor_unitario numeric(12, 2) not null default 0,
  constraint vendas_quantidade_vendida_check check (quantidade_vendida > 0)
);

alter table public.vendas add column if not exists cliente_id bigint;
alter table public.vendas add column if not exists valor_total numeric(12, 2);
alter table public.vendas add column if not exists observacoes text;
alter table public.vendas add column if not exists created_at timestamptz default now();

create table if not exists public.custos_venda (
  id bigint generated by default as identity primary key,
  venda_id bigint not null references public.vendas(id),
  tipo_custo text not null,
  descricao text,
  valor numeric(12, 2) not null default 0,
  data_custo date not null default current_date,
  created_at timestamptz not null default now(),
  constraint custos_venda_valor_check check (valor >= 0)
);

alter table public.custos_venda add column if not exists created_at timestamptz default now();
