-- Tabelas iniciais para salvar dados reais no Supabase.
-- A peca usa origem_id como vinculo com a origem. O texto da origem fica apenas para exibicao.

create table if not exists public.origens (
  id bigint generated by default as identity primary key,
  tipo_origem text,
  tipo text not null,
  descricao text not null,
  custo_total numeric(12, 2),
  custo_tipo text,
  valor_pago numeric(12, 2) not null default 0,
  data_compra date not null default current_date,
  observacoes text,
  criado_em timestamptz not null default now()
);

alter table public.origens add column if not exists tipo_origem text;
alter table public.origens add column if not exists tipo text;
alter table public.origens add column if not exists descricao text;
alter table public.origens add column if not exists custo_total numeric(12, 2);
alter table public.origens add column if not exists custo_tipo text;
alter table public.origens add column if not exists valor_pago numeric(12, 2) default 0;
alter table public.origens add column if not exists data_compra date default current_date;
alter table public.origens add column if not exists observacoes text;
alter table public.origens add column if not exists criado_em timestamptz default now();

update public.origens
set tipo = coalesce(tipo, tipo_origem, 'Origem')
where tipo is null;

update public.origens
set valor_pago = coalesce(valor_pago, custo_total, 0)
where valor_pago is null;

update public.origens
set data_compra = current_date
where data_compra is null;

alter table public.origens alter column valor_pago set default 0;
alter table public.origens alter column data_compra set default current_date;

create table if not exists public.pecas (
  id bigint generated by default as identity primary key,
  origem_id bigint not null references public.origens(id),
  nome text not null,
  sku text,
  categoria text not null,
  quantidade integer not null default 1,
  quantidade_vendida integer not null default 0,
  status text not null default 'em_estoque',
  custo_total numeric(12, 2),
  custo numeric(12, 2) not null default 0,
  tipo_custo text not null default 'real',
  preco_venda numeric(12, 2) not null default 0,
  observacoes text,
  criado_em timestamptz not null default now(),
  constraint pecas_tipo_custo_check check (tipo_custo in ('real', 'rateado', 'simbolico')),
  constraint pecas_quantidade_check check (quantidade >= 0),
  constraint pecas_quantidade_vendida_check check (quantidade_vendida >= 0)
);

alter table public.pecas add column if not exists custo_total numeric(12, 2);
alter table public.pecas add column if not exists custo numeric(12, 2) default 0;

update public.pecas
set custo_total = coalesce(custo_total, custo, 0)
where custo_total is null;

update public.pecas
set custo = coalesce(custo, custo_total, 0)
where custo is null;

alter table public.pecas alter column custo set default 0;

create table if not exists public.custos_peca (
  id bigint generated by default as identity primary key,
  peca_id bigint not null references public.pecas(id),
  tipo_custo text not null,
  descricao text,
  valor numeric(12, 2) not null default 0,
  data_custo date not null default current_date,
  criado_em timestamptz not null default now(),
  constraint custos_peca_valor_check check (valor >= 0)
);

create table if not exists public.vendas (
  id bigint generated by default as identity primary key,
  peca_id bigint not null references public.pecas(id),
  quantidade_vendida integer not null,
  valor_unitario numeric(12, 2) not null default 0,
  canal_venda text,
  data_venda date not null default current_date,
  criado_em timestamptz not null default now(),
  constraint vendas_quantidade_vendida_check check (quantidade_vendida > 0)
);

create table if not exists public.custos_venda (
  id bigint generated by default as identity primary key,
  venda_id bigint not null references public.vendas(id),
  tipo_custo text not null,
  descricao text,
  valor numeric(12, 2) not null default 0,
  data_custo date not null default current_date,
  criado_em timestamptz not null default now(),
  constraint custos_venda_valor_check check (valor >= 0)
);
