-- Estrutura inicial para controle FIFO.
-- Esta etapa apenas cria as tabelas de entradas/lotes e consumos por venda.
-- A funcao de venda FIFO sera criada em uma proxima etapa.

alter table public.origens add column if not exists produto_sku text;
alter table public.origens add column if not exists quantidade_total integer default 0;
alter table public.origens alter column custo_tipo set default 'compra';
alter table public.pecas add column if not exists sku text;

alter table public.origens drop constraint if exists origens_custo_tipo_check;
alter table public.origens drop constraint if exists origens_tipo_origem_check;
alter table public.origens drop constraint if exists origens_tipo_check;

update public.origens
set quantidade_total = 0
where quantidade_total is null;

update public.origens
set custo_tipo = 'compra'
where custo_tipo is null or trim(custo_tipo) = '';

alter table public.origens
add constraint origens_custo_tipo_check
check (
  custo_tipo in (
    'compra',
    'frete',
    'outro',
    'real',
    'rateado',
    'simbolico'
  )
);

alter table public.origens
add constraint origens_tipo_origem_check
check (
  tipo_origem is null
  or tipo_origem in (
    'Compra avulsa',
    'Carro para desmonte',
    'Lote',
    'Estoque Inicial',
    'compra_avulsa',
    'carro_para_desmonte',
    'carro_desmonte',
    'lote',
    'estoque_inicial'
  )
);

alter table public.origens
add constraint origens_tipo_check
check (
  tipo is null
  or tipo in (
    'Compra avulsa',
    'Carro para desmonte',
    'Lote',
    'Estoque Inicial',
    'compra_avulsa',
    'carro_para_desmonte',
    'carro_desmonte',
    'lote',
    'estoque_inicial'
  )
);

alter table public.origens alter column quantidade_total set default 0;

create table if not exists public.entradas_estoque (
  id bigint generated by default as identity primary key,
  peca_id bigint not null references public.pecas(id),
  origem_id bigint references public.origens(id),
  quantidade_total integer not null,
  quantidade_consumida integer not null default 0,
  custo_unitario numeric(12, 2) not null,
  data_entrada date not null default current_date,
  created_at timestamptz not null default now(),
  constraint entradas_estoque_quantidade_total_check check (quantidade_total > 0),
  constraint entradas_estoque_quantidade_consumida_check check (quantidade_consumida >= 0),
  constraint entradas_estoque_saldo_check check (quantidade_consumida <= quantidade_total),
  constraint entradas_estoque_custo_unitario_check check (custo_unitario >= 0)
);

create index if not exists entradas_estoque_peca_fifo_idx
on public.entradas_estoque (peca_id, data_entrada, id);

create index if not exists entradas_estoque_origem_idx
on public.entradas_estoque (origem_id);

create table if not exists public.venda_consumos_estoque (
  id bigint generated by default as identity primary key,
  venda_id bigint not null references public.vendas(id),
  entrada_estoque_id bigint not null references public.entradas_estoque(id),
  quantidade_consumida integer not null,
  custo_unitario numeric(12, 2) not null,
  custo_total numeric(12, 2) not null,
  created_at timestamptz not null default now(),
  constraint venda_consumos_quantidade_check check (quantidade_consumida > 0),
  constraint venda_consumos_custo_unitario_check check (custo_unitario >= 0),
  constraint venda_consumos_custo_total_check check (custo_total >= 0)
);

create index if not exists venda_consumos_venda_idx
on public.venda_consumos_estoque (venda_id);

create index if not exists venda_consumos_entrada_idx
on public.venda_consumos_estoque (entrada_estoque_id);

create or replace view public.vw_saldos_entradas_estoque as
select
  entrada.id,
  entrada.peca_id,
  entrada.origem_id,
  entrada.quantidade_total,
  entrada.quantidade_consumida,
  entrada.quantidade_total - entrada.quantidade_consumida as quantidade_disponivel,
  entrada.custo_unitario,
  entrada.data_entrada,
  entrada.created_at
from public.entradas_estoque entrada;

notify pgrst, 'reload schema';
