-- Cadastro controlado de tipos de custo.
-- Mantem as colunas texto antigas para nao quebrar custos ja cadastrados.

create table if not exists public.tipos_custo (
  id bigint generated by default as identity primary key,
  nome text not null,
  categoria text not null default 'ambos',
  ativo boolean not null default true,
  created_at timestamptz not null default now(),
  constraint tipos_custo_categoria_check check (categoria in ('peca', 'venda', 'ambos'))
);

alter table public.tipos_custo
add column if not exists categoria text not null default 'ambos';

alter table public.tipos_custo
drop constraint if exists tipos_custo_categoria_check;

alter table public.tipos_custo
add constraint tipos_custo_categoria_check check (categoria in ('peca', 'venda', 'ambos'));

create unique index if not exists tipos_custo_nome_unico_idx
on public.tipos_custo (lower(trim(nome)));

insert into public.tipos_custo (nome, categoria)
select tipo.nome, tipo.categoria
from (
  values
    ('Limpeza', 'peca'),
    ('Solda', 'peca'),
    ('Pintura', 'peca'),
    ('Conserto', 'peca'),
    ('Preparo', 'peca'),
    ('Embalagem', 'venda'),
    ('Frete', 'venda'),
    ('Comissão', 'venda'),
    ('Taxa marketplace', 'venda'),
    ('Taxa cartão', 'venda'),
    ('Coleta', 'venda'),
    ('Etiqueta', 'venda'),
    ('Outros', 'venda')
) as tipo(nome, categoria)
where not exists (
  select 1
  from public.tipos_custo existente
  where lower(trim(existente.nome)) = lower(trim(tipo.nome))
);

update public.tipos_custo existente
set categoria = tipo.categoria
from (
  values
    ('Limpeza', 'peca'),
    ('Solda', 'peca'),
    ('Pintura', 'peca'),
    ('Conserto', 'peca'),
    ('Preparo', 'peca'),
    ('Embalagem', 'venda'),
    ('Frete', 'venda'),
    ('Comissão', 'venda'),
    ('Taxa marketplace', 'venda'),
    ('Taxa cartão', 'venda'),
    ('Coleta', 'venda'),
    ('Etiqueta', 'venda'),
    ('Outros', 'venda')
) as tipo(nome, categoria)
where lower(trim(existente.nome)) = lower(trim(tipo.nome));

-- Preserva flexibilidade: tipos antigos que ja existem nos custos tambem entram no cadastro.
insert into public.tipos_custo (nome, categoria)
select distinct custos_antigos.nome, custos_antigos.categoria
from (
  select
    case
      when lower(trim(tipo_custo)) in ('comissao', 'comissão') then 'Comissão'
      when lower(trim(tipo_custo)) in ('outro', 'outros') then 'Outros'
      else upper(left(trim(tipo_custo), 1)) || lower(substr(trim(tipo_custo), 2))
    end as nome,
    categoria
  from (
    select tipo_custo, 'peca' as categoria from public.custos_peca
    union all
    select tipo_custo, 'venda' as categoria from public.custos_venda
  ) custos
  where tipo_custo is not null
    and trim(tipo_custo) <> ''
) custos_antigos
where not exists (
  select 1
  from public.tipos_custo existente
  where lower(trim(existente.nome)) = lower(trim(custos_antigos.nome))
);
alter table public.custos_peca
add column if not exists tipo_custo_id bigint references public.tipos_custo(id);

alter table public.custos_peca
add column if not exists observacoes text;

alter table public.custos_venda
add column if not exists tipo_custo_id bigint references public.tipos_custo(id);

alter table public.custos_venda
add column if not exists observacoes text;

update public.custos_peca custo
set tipo_custo_id = tipo.id
from public.tipos_custo tipo
where custo.tipo_custo_id is null
  and lower(trim(
    case
      when lower(trim(custo.tipo_custo)) in ('comissao', 'comissão') then 'Comissão'
      when lower(trim(custo.tipo_custo)) in ('outro', 'outros') then 'Outros'
      else custo.tipo_custo
    end
  )) = lower(trim(tipo.nome));

update public.custos_venda custo
set tipo_custo_id = tipo.id
from public.tipos_custo tipo
where custo.tipo_custo_id is null
  and lower(trim(
    case
      when lower(trim(custo.tipo_custo)) in ('comissao', 'comissão') then 'Comissão'
      when lower(trim(custo.tipo_custo)) in ('outro', 'outros') then 'Outros'
      else custo.tipo_custo
    end
  )) = lower(trim(tipo.nome));
